name: letscheck
description: A Checkmk client for many Platforms.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.4+1271

environment:
  sdk: ^3.6.0
  flutter: "3.27.3" # Workflow "subosito/flutter-action@v2" needs a exact version here.

dependencies:
  flutter:
    sdk: flutter
  check_mk_api:
    path: ../check_mk_api-flutter/
    # git: 
    #   url: https://github.com/jochumdev/check_mk_api-flutter.git
  built_value: ^8.9.3
  built_collection: ^5.1.1
  flutter_form_bloc:
    git:
      url: https://github.com/jochumdev/flutter_form_bloc.git
      path: packages/flutter_form_bloc
  hydrated_bloc: ^10.0.0
  path_provider: ^2.0.13
  equatable: ^2.0.3
  numberpicker: ^2.1.1
  retry: ^3.0.1
  font_awesome_flutter: ^10.4.0
  grouped_list: ^6.0.0
  package_info_plus: ^8.1.3
  flutter_timezone: ^4.0.0
  flutter_js: ^0.8.1
  flutter_local_notifications:
    git:
     url: https://github.com/MaikuB/flutter_local_notifications.git
     path: flutter_local_notifications
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  timezone: ^0.10.0
  window_manager: ^0.4.3
  mutex: ^3.1.0
  google_fonts: ^6.2.1
  flutter_background_service: ^5.1.0
  tray_manager: ^0.3.2
  flutter_settings_ui: ^3.0.1
  go_router: ^14.7.2

dev_dependencies:
  built_value_generator: ^8.4.3
  build_runner: ^2.3.3
  lints: ^5.0.0
  msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/js/
    - assets/sound/
    - assets/fonts/
    - assets/misc/
    - CHANGELOG.md

flutter_intl:
  enabled: true

# Empty line required by workflows.
