name: letscheck
description: Let's Check your Check_MK Client.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  check_mk_api:
    path: ../check_mk_api
  built_value: ^7.1.0
  built_collection: ^4.3.2
  flutter_form_bloc: ^0.19.0
  hydrated_bloc: ^6.0.1
  path_provider: ^1.6.18
  equatable: ^1.2.5
  settings_ui: ^0.4.0
  numberpicker: ^1.2.1
  retry: ^3.0.1
  font_awesome_flutter: ^8.8.1
  grouped_list: ^3.5.0
  intl: ^0.16.1
  package_info: '>=0.4.3 <2.0.0'
  flutter_js: 0.2.2+0

  flutter_slidable: ^0.5.7

  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.5.0+1
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.1.0
  build_runner: ^1.10.1
  flutter_bloc_monitor: ^1.0.3+1
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/js/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
